ethereum_rpc = "https://rpc.hoodi.ethpandaops.io/"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.omniguard_tri_fault_hardened]
path = "out/OmniGuardTrap.sol/OmniGuardTrap.json"
response_contract = "0x1AA425d0F1Caa1489d7D6A3b82aAf4F426cc4531"
response_function = "executeResponse(address,bytes)"
cooldown_period_blocks = 50
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private = true
whitelist = ["0x0f9F0bA411245CeC1F78B2397f109c29b4eD9f31"]
private_trap = true
address = "0xc379a8d919D1808b88195F1b4488F2f519D1404a"
